### PR TITLE
Exclude nulls from metric variants

### PR DESCRIPTION
**Pull request by davecromberge**
Includes move of SQL templates from pg module to the builder for consistency + tests.

### CODE REVIEW

**Comment by Licenser** [comment]
very nice improvement!

**Comment by Licenser** [comment]
The tests fail, you can not include tests that depend on local setups. Everything needs to be bootstrapped within the test or mocked out.

```
===== query_builder_eqc:prop_collections

=ERROR REPORT==== 4-Oct-2016::17:00:44 ===
** Generic server <0.289.0> terminating
** Last message in was {connect,"localhost","ddb",[],
                                [{port,5432},{database,"metric_metadata"}]}
** When Server state == {state,undefined,undefined,<<>>,undefined,undefined,
                               undefined,
                               {[],[]},
                               undefined,[],[],[],[],[],[],undefined,
                               undefined}
```

**Comment by davecromberge** [comment]
I agree in principle, but in this case the "well-formedness" or integrity of the queries are validated.  In order to verify that the queries conform to the schema it needs to connect to an actual database schema.  The only way around this is to create an in-memory db, but that would require a different database driver making these tests invalid.  I don't know how to work around this limitation - do you think the value of the tests outweighs the limitation here?

**Comment by Licenser** [comment]
If it's just about checking syntax validity something like pgsanity[1] might be a better alternative? Could be bundled in so it wont' require to be installed or downlaoded.

That would still add a dependency (python) but I think that's a lot less problematic then having a running sql server with a certain user and database.

[1] https://github.com/markdrago/pgsanity

**Comment by davecromberge** [comment]
Great idea, it does sound better - will investigate this alternative 👍

**Comment by Licenser** [comment]
I reverted this pull request, please re-open once the test pass.

**Comment by davecromberge** [comment]
For what it's worth, I would like to offer some an argument as to why I value these tests in their current form at the cost of the inconvenience of having a db connection. It is worth pointing out that the tests will lose some efficacy if we go down the route of purely syntactic checks.

There is some additional benefit to connecting to a schema - these tests found a query that did not work because it used the ambiguous `namespace` column without fully qualifying the table name.  This would not have been possible with a purely syntactic check.
It is common practice in many libraries to connect to the database with the latest schema in order to verify the syntactic correctness as well as constraint correctness.
For example, see http://underscore.io/blog/posts/2015/05/28/typechecking-sql.html.  Unfortunately Postgres does not have an in-memory driver which makes it inconvenient to bootstrap a test database in flight.  For example, see https://github.com/epgsql/epgsql#test-setup

_Obviously this implies that a valid connection is needed in order to run the tests._

Using a library such as `pgsanity` requires the interpolation of the sql fragment and values to be done in the test suite in order to yield the raw sql, this may differ from the [wire protocol](https://github.com/epgsql/epgsql/blob/master/src/epgsql_wire.erl#L179) making the tests diverge further from the actual runtime behaviour.

**Comment by Licenser** [comment]
I don't say they have no benefit, but as they are at this point they are a total no go. They are not configurable. The requirements and setup is not documented. They assumes something existing setup. Will they destroy existing data if you happen to have data in there? That'd be 'great'! Imagine someone running a test on a system w/ production data and all the data getting eaten up.

If you look at the epgsql example you linked they are **very** explicit about what tests require a database and even use a clean new pg instance to not colidea with existing data.

People are lazy, if tests require them to dig through code to figure out what to set up, they won't run tests. If they got to download and run additional software they won't run tests. Chances are if it's more then 'make test' (or rebar3 as eqc eqc) they won't run tests. Remember how long you weren't running eqc tests because you had to install eqc for it ;). I'm just the same if it's more hassle then worth to run tests I don't run them - I've stopped using riak_test for that reason. Bad tests that are executed are better then good tests that are never run. (in a perfect word of cause we've good tests that are run).

I'm not totally against db requiring tests but I am convinced they need to be separated from other tests (own profile?), be well documented (even I would have had to read the source to figure out what to set up and I know the codebase very well), have an automated setup and teardown (5 minutes manual table creation, filling and emptying for a test run is a total showstopper), do not mess with production services (If my database had run it might have silently destroyed the data I have there for application tests wich would be bad).

**Comment by davecromberge** [comment]
Reopened with the above comments taken into consideration:
https://github.com/dalmatinerdb/dqe_idx_pg/pull/25

**Pull request merged**
