### PR TITLE
Proposal to fix adding new dimensions to existing metrics

### PR DESCRIPTION
**Pull request by starstuck**
I run into a problem when there was new tag, or if you prefer meta-data introduced to existing metric. New tags are just silently dropped in current implementation.

It is so, because current posgresql query is not returning metric id when new tags are added to a metric that is already in database.

I am not postgresql expert. A workaround I found seems a bit dirty. Maybe you know better solution. The only other way I could think of, would be treating a case of conflict separately and run additional query to get id.

### CODE REVIEW

**Comment by starstuck** [comment]
This issue is because we try to use dimensional and two-dimensional tags alongside each other. Former are regular tags that constitute to new metric series dimension/identity. When new on of those is added, it is not affected by this issue, because it comes with different ddb key.

This issue is with non-dimensional stuff, like hostname or ui annotation which act more as a metric meta-data. WHenever they change, they are not changing metric key, those causing said issue.

It just kept me thinking, that maybe my workaround is too high price for keeping those 2 semantically different things in one bag. Maybe we should keep it separately and come up with more efficient dedicated approach for keeping metric meta-data in sync. Having said that, it is very convenient to use both in a same way for querying series.

What do you think?

**Comment by Licenser** [comment]
Have you looked at the update function?

https://github.com/dalmatinerdb/dqe_idx_pg/blob/master/src/dqe_idx_pg.erl#L309

https://github.com/dalmatinerdb/dqe_idx/blob/master/src/dqe_idx.erl#L365

**Comment by starstuck** [comment]
I wasn't aware that there is separate function for handling updates. I think I can get away with that new function.

**Comment by Licenser** [comment]
not that new, is there since may but great if that does what you want. Beware that it's more expesnive, and should be used sparingly as changing tags can break user experience.

**Pull request closed without merging**
